spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:0.6b
      embedding:
        model: qwen3-embedding:0.6b
    vectorstore:
      pgvector:
        host: localhost
        port: 5434
        database: vectordb
        username: postgres
        password: postgres
        initialize-schema: true
        index-type: hnsw
        dimensions: 1024

management:
  health:
    db:
      enabled: false

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  ai:
#    # Ollama 聊天
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen2.5:0.5b
#      embedding:
#        model: qwen3-embedding:0.6b
#
#    # PGVector 向量库
#    vectorstore:
#      pgvector:
#        index-type: hnsw
#        distance-type: COSINE_DISTANCE